### ISSUE TITLE
No SQL Script

### ISSUE THREAD

**Issue by SvenLauterbach** [Early-Modern-OCR/FrankenPlus#2]
Hi, apparently the project is missing a sql file containing all required tables. Also, it would be great if the programm could show a error message or something. Currently nothing happens if a db operaation fails.

**Comment by bptarpley** [comment]
Hi, Sven!  You're definitely right about the error reporting--very sorry about that.  Once I get some time to make this project more robust, that'll be one of my main concerns.

As for the sql file you're referencing, it doesn't exist because Franken+ creates all the tables you need when you go to Menu->Settings->Database and click on "Reset Database."  Perhaps I should use the language "Setup Database" instead on that button?

**Comment by SvenLauterbach** [comment]
After taking a look at the source I figured out how it works and closed this issue - but yes, you should rename that Button :).
